try:
    import time
    from inspect import currentframe , getframeinfo

    result_count = 0
    x_point = 0
    o_point = 0
    repeat = str("str")
    while repeat != "NO" :
        print()
        '''
        for getting LINE :
                error = getframeinfo(currentframe())
                print("Program crashed !          CHECKING : (line",error.lineno+")")
        '''
        print()

        mode_selector = str("str")
        while mode_selector != 'N' and mode_selector != 'F' :
            print("Enter \'N\' to run program Normaly or enter ")
            mode_selector = input("\'F\' to perform code in Fast mode : ")
            print()
            mode_selector = mode_selector.upper()

        if mode_selector=='F' :
            time.sleep(0.5)
            print("          Normal mode  :   (\U00002718)")
            time.sleep(0.3)
            print("          Fast mode    :   (\U00002714)")
            time.sleep(0.7)
            def short_puse() :
                pass
            def puse():
                pass
            def long_puse() :
                pass
            def checking () :
                pass
        elif mode_selector=='N' :
            time.sleep(0.5)
            print("          Normal mode  :   (\U00002714)")
            time.sleep(0.3)
            print("          Fast mode    :   (\U00002718)")
            time.sleep(0.7)
            def short_puse() :
                time.sleep(0.04)
            def puse():
                time.sleep(0.27)
            def long_puse() :
                pass
            def checking() :
                puse()
                print("F", end="")
                puse()
                print("i", end="")
                puse()
                print("r", end="")
                puse()
                print("s", end="")
                puse()
                print("t", end="")
                puse()
                print(" ", end="")
                puse()
                print("p", end="")
                puse()
                print("l", end="")
                puse()
                print("a", end="")
                puse()
                print("y", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("i", end="")
                puse()
                print("s", end="")
                puse()
                print(" ", end="")
                puse()
                print("\"", end="")
                puse()
                print("X", end="")
                puse()
                print("\"", end="")
                puse()
                print(" ", end="")
                puse()
                print("a", end="")
                puse()
                print("n", end="")
                puse()
                print("d", end="")
                puse()
                print(" ", end="")
                puse()
                print("h", end="")
                puse()
                print("i", end="")
                puse()
                print("s", end="")
                puse()
                print("/", end="")
                puse()
                print("h", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("i", end="")
                puse()
                print("c", end="")
                puse()
                print("o", end="")
                puse()
                print("n", end="")
                puse()
                print(" ", end="")
                puse()
                print("i", end="")
                puse()
                print("s", end="")
                puse()
                print(" ", end="")
                puse()
                print("\U0001F7E5")
                puse()
                puse()
                print("E", end="")
                puse()
                print("n", end="")
                puse()
                print("t", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("\'", end="")
                puse()
                print("c", end="")
                puse()
                print("h", end="")
                puse()
                print("e", end="")
                puse()
                print("c", end="")
                puse()
                print("k", end="")
                puse()
                print("\'", end="")
                puse()
                print(" ", end="")
                puse()
                print("t", end="")
                puse()
                print("o", end="")
                puse()
                print(" ", end="")
                puse()
                print("c", end="")
                puse()
                print("o", end="")
                puse()
                print("n", end="")
                puse()
                print("t", end="")
                puse()
                print("i", end="")
                puse()
                print("n", end="")
                puse()
                print("u", end="")
                puse()
                print("e", end="")
                puse()
                print(" ", end="")
                puse()
                print(":", end="")
                puse()
                print(" ", end="")
                p1 = input("")
                p1 = p1.lower()
                while p1 != "check":
                    print("E", end="")
                    short_puse()
                    print("n", end="")
                    short_puse()
                    print("t", end="")
                    short_puse()
                    print("e", end="")
                    short_puse()
                    print("r", end="")
                    short_puse()
                    print(" ", end="")
                    short_puse()
                    print("\'", end="")
                    short_puse()
                    print("c", end="")
                    short_puse()
                    print("h", end="")
                    short_puse()
                    print("e", end="")
                    short_puse()
                    print("c", end="")
                    short_puse()
                    print("k", end="")
                    short_puse()
                    print("\'", end="")
                    short_puse()
                    print(" ", end="")
                    short_puse()
                    print("t", end="")
                    short_puse()
                    print("o", end="")
                    short_puse()
                    print(" ", end="")
                    short_puse()
                    print("c", end="")
                    short_puse()
                    print("o", end="")
                    short_puse()
                    print("n", end="")
                    short_puse()
                    print("t", end="")
                    short_puse()
                    print("i", end="")
                    short_puse()
                    print("n", end="")
                    short_puse()
                    print("u", end="")
                    short_puse()
                    print("e", end="")
                    short_puse()
                    print(" ", end="")
                    short_puse()
                    print(":", end="")
                    short_puse()
                    print(" ", end="")
                    p1 = input("")
                    p1 = p1.lower()
                puse()
                fortyfive = 0
                while fortyfive < 44:
                    print("*", end="")
                    short_puse()
                    fortyfive += 1
                print("*")
                puse()
                print("S", end="")
                puse()
                print("e", end="")
                puse()
                print("c", end="")
                puse()
                print("o", end="")
                puse()
                print("n", end="")
                puse()
                print("d", end="")
                puse()
                print(" ", end="")
                puse()
                print("p", end="")
                puse()
                print("l", end="")
                puse()
                print("a", end="")
                puse()
                print("y", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("i", end="")
                puse()
                print("s", end="")
                puse()
                print(" ", end="")
                puse()
                print("\"", end="")
                puse()
                print("O", end="")
                puse()
                print("\"", end="")
                puse()
                print(" ", end="")
                puse()
                print("a", end="")
                puse()
                print("n", end="")
                puse()
                print("d", end="")
                puse()
                print(" ", end="")
                puse()
                print("h", end="")
                puse()
                print("i", end="")
                puse()
                print("s", end="")
                puse()
                print("/", end="")
                puse()
                print("h", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("i", end="")
                puse()
                print("c", end="")
                puse()
                print("o", end="")
                puse()
                print("n", end="")
                puse()
                print(" ", end="")
                puse()
                print("i", end="")
                puse()
                print("s", end="")
                puse()
                print(" ", end="")
                puse()
                print("\U0001F7E8")
                puse()
                puse()
                print("E", end="")
                puse()
                print("n", end="")
                puse()
                print("t", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("\'", end="")
                puse()
                print("c", end="")
                puse()
                print("h", end="")
                puse()
                print("e", end="")
                puse()
                print("c", end="")
                puse()
                print("k", end="")
                puse()
                print("\'", end="")
                puse()
                print(" ", end="")
                puse()
                print("t", end="")
                puse()
                print("o", end="")
                puse()
                print(" ", end="")
                puse()
                print("c", end="")
                puse()
                print("o", end="")
                puse()
                print("n", end="")
                puse()
                print("t", end="")
                puse()
                print("i", end="")
                puse()
                print("n", end="")
                puse()
                print("u", end="")
                puse()
                print("e", end="")
                puse()
                print(" ", end="")
                puse()
                print(":", end="")
                puse()
                print(" ", end="")
                p2 = input("")
                p2 = p2.lower()
                while p2 != "check":
                    print("E", end="")
                    short_puse()
                    print("n", end="")
                    short_puse()
                    print("t", end="")
                    short_puse()
                    print("e", end="")
                    short_puse()
                    print("r", end="")
                    short_puse()
                    print(" ", end="")
                    short_puse()
                    print("\'", end="")
                    short_puse()
                    print("c", end="")
                    short_puse()
                    print("h", end="")
                    short_puse()
                    print("e", end="")
                    short_puse()
                    print("c", end="")
                    short_puse()
                    print("k", end="")
                    short_puse()
                    print("\'", end="")
                    short_puse()
                    print(" ", end="")
                    short_puse()
                    print("t", end="")
                    short_puse()
                    print("o", end="")
                    short_puse()
                    print(" ", end="")
                    short_puse()
                    print("c", end="")
                    short_puse()
                    print("o", end="")
                    short_puse()
                    print("n", end="")
                    short_puse()
                    print("t", end="")
                    short_puse()
                    print("i", end="")
                    short_puse()
                    print("n", end="")
                    short_puse()
                    print("u", end="")
                    short_puse()
                    print("e", end="")
                    short_puse()
                    print(" ", end="")
                    short_puse()
                    print(":", end="")
                    short_puse()
                    print(" ", end="")
                    p2 = input("")
                    p2 = p2.lower()
                puse()
                fortyfive = 0
                while fortyfive < 44:
                    print("*", end="")
                    short_puse()
                    fortyfive += 1
                print("*")
        else:
            error = getframeinfo(currentframe())
            print("Program crashed !          CHECKING : mode_selector (line33",error.lineno+")")

        def already () :
            short_puse()
            print("", end="T")
            short_puse()
            print("", end="h")
            short_puse()
            print("", end="i")
            short_puse()
            print("", end="s")
            short_puse()
            print("", end=" ")
            short_puse()
            print("", end="l")
            short_puse()
            print("", end="o")
            short_puse()
            print("", end="c")
            short_puse()
            print("", end="a")
            short_puse()
            print("", end="t")
            short_puse()
            print("", end="i")
            short_puse()
            print("", end="o")
            short_puse()
            print("", end="n")
            short_puse()
            print("", end=" ")
            short_puse()
            print("", end="h")
            short_puse()
            print("", end="a")
            short_puse()
            print("", end="s")
            short_puse()
            print("", end=" ")
            short_puse()
            print("", end="a")
            short_puse()
            print("", end="l")
            short_puse()
            print("", end="r")
            short_puse()
            print("", end="e")
            short_puse()
            print("", end="a")
            short_puse()
            print("", end="d")
            short_puse()
            print("", end="y")
            short_puse()
            print("", end=" ")
            short_puse()
            print("", end="b")
            short_puse()
            print("", end="e")
            short_puse()
            print("", end="e")
            short_puse()
            print("", end="n")
            short_puse()
            print("", end=" ")
            short_puse()
            print("", end="s")
            short_puse()
            print("", end="e")
            short_puse()
            print("", end="l")
            short_puse()
            print("", end="e")
            short_puse()
            print("", end="c")
            short_puse()
            print("", end="t")
            short_puse()
            print("", end="e")
            short_puse()
            print("", end="d")
            short_puse()
            print("", end=" ")
            short_puse()
            print("⚠️")
            short_puse()

        enter_space = 0
        while enter_space<=30:
            print(".                                           .")
            short_puse()
            enter_space += 1

        puse()
        print("W" , end="")
        puse()
        print("e" , end="")
        puse()
        print("l" , end="")
        puse()
        print("c" , end="")
        puse()
        print("o" , end="")
        puse()
        print("m" , end="")
        puse()
        print("e" , end="")
        puse()
        print(" " , end="")
        puse()
        print("\U0001F44B" , end="")
        time.sleep(0.35)
        print("                               ",end="")
        time.sleep(0.35)
        print("\U0001F1E7" , end="")
        time.sleep(0.35)
        print("\U0001F1EA" , end="")
        time.sleep(0.35)
        print("\U0001F1F9" , end="")
        time.sleep(0.35)
        print("\U0001F1E6" , end="")
        time.sleep(0.35)
        print("\U0000FE62" , end="")
        time.sleep(0.35)
        print()
        fortyfive = 0
        while fortyfive < 44:
            print("*", end="")
            short_puse()
            fortyfive += 1
        print("*")
        short_puse()
        print("                  ",end="")
        short_puse()
        print("X",end="")
        puse()
        print("O",end="")
        puse()
        print(" ",end="")
        puse()
        print("G",end="")
        puse()
        print("a",end="")
        puse()
        print("m",end="")
        puse()
        print("e",end="")
        puse()
        print(" ",end="")
        puse()
        print("!",end="")
        short_puse()
        print("                  ")
        short_puse()
        fortyfive = 0
        while fortyfive < 44:
            print("*", end="")
            short_puse()
            fortyfive += 1
        print("*")
        short_puse()

        checking()

        print()
        short_puse()
        print("+", end="")
        fortyfive = 0
        while fortyfive < 43:
            print("-", end="")
            short_puse()
            fortyfive += 1
        print("+")
        short_puse()
        print("|              ", end="")
        short_puse()
        print("\U0001F3C6", end="")
        puse()
        print(" ", end="")
        puse()
        print("S", end="")
        puse()
        print("c", end="")
        puse()
        print("o", end="")
        puse()
        print("r", end="")
        puse()
        print("e", end="")
        puse()
        print("b", end="")
        puse()
        print("o", end="")
        puse()
        print("a", end="")
        puse()
        print("r", end="")
        puse()
        print("d", end="")
        puse()
        print(" ", end="")
        puse()
        print("\U0001F3C6", end="")
        puse()
        print("              |")
        short_puse()
        print("|   ", end="")
        short_puse()
        print("P", end="")
        puse()
        print("l", end="")
        puse()
        print("a", end="")
        puse()
        print("y", end="")
        puse()
        print("e", end="")
        puse()
        print("r", end="")
        puse()
        print(" ", end="")
        puse()
        print("\'", end="")
        puse()
        print("X", end="")
        puse()
        print("\'", end="")
        puse()
        print(" ", end="")
        puse()
        print(":", end="")
        puse()
        print(" ", end="")
        puse()
        print(str(x_point), end="")
        short_puse()
        print("        ", end="")
        short_puse()
        print("P", end="")
        puse()
        print("l", end="")
        puse()
        print("a", end="")
        puse()
        print("y", end="")
        puse()
        print("e", end="")
        puse()
        print("r", end="")
        puse()
        print(" ", end="")
        puse()
        print("\'", end="")
        puse()
        print("O", end="")
        puse()
        print("\'", end="")
        puse()
        print(" ", end="")
        puse()
        print(":", end="")
        puse()
        print(" ", end="")
        puse()
        print(str(o_point), end="")
        short_puse()
        print("    |")
        short_puse()
        print("+", end="")
        fortyfive = 0
        while fortyfive < 43:
            print("-", end="")
            short_puse()
            fortyfive += 1
        print("+")
        short_puse()
        print()

        puse()
        print("* * * * * * * * * * * * * * * * * * * * * * *")
        puse()
        print("*                                           *")
        puse()
        print("*                 1 | 2 | 3                 *")
        puse()
        print("*                ___|___|___                *")
        puse()
        print("*                 4 | 5 | 6                 *")
        puse()
        print("*                ___|___|___                *")
        puse()
        print("*                 7 | 8 | 9                 *")
        puse()
        print("*                   |   |                   *")
        puse()
        print("*                                           *")
        puse()
        print("* * * * * * * * * * * * * * * * * * * * * * *")

        x = {
            "x_1":False,
            "x_2":False,
            "x_3":False,
            "x_4":False,
            "x_5":False,
            "x_6":False,
            "x_7":False,
            "x_8":False,
            "x_9":False
        }
        o = {
            "o_1":False,
            "o_2":False,
            "o_3":False,
            "o_4":False,
            "o_5":False,
            "o_6":False,
            "o_7":False,
            "o_8":False,
            "o_9":False
        }
        d = {
            "d_1":False,
            "d_2":False,
            "d_3":False,
            "d_4":False,
            "d_5":False,
            "d_6":False,
            "d_7":False,
            "d_8":False,
            "d_9":False
        }

        print_list = {
            "i1" : "1 ",
            "i2" : "2 ",
            "i3" : "3 ",
            "i4" : "4 ",
            "i5" : "5 ",
            "i6" : "6 ",
            "i7" : "7 ",
            "i8" : "8 ",
            "i9" : "9 "
        }

        def draw () :
            short_puse()
            print("* * * * * * * * * * * * * * * * * * * * * * *")
            short_puse()
            print("*                                           *")
            short_puse()
            print("*                " + print_list["i1"] + " | " + print_list["i2"] + " | " + print_list["i3"] + "               *")
            short_puse()
            print("*               ____|____|____              *")
            short_puse()
            print("*                " + print_list["i4"] + " | " + print_list["i5"] + " | " + print_list["i6"] + "               *")
            short_puse()
            print("*               ____|____|____              *")
            short_puse()
            print("*                " + print_list["i7"] + " | " + print_list["i8"] + " | " + print_list["i9"] + "               *")
            short_puse()
            print("*                   |    |                  *")
            short_puse()
            print("*                                           *")
            short_puse()
            print("* * * * * * * * * * * * * * * * * * * * * * *")
            short_puse()

        while (( x["x_1"] and x["x_2"] and x["x_3"] ) or (
                x["x_4"] and x["x_5"] and x["x_6"] ) or (
                x["x_7"] and x["x_8"] and x["x_9"] ) or (
                x["x_1"] and x["x_4"] and x["x_7"] ) or (
                x["x_2"] and x["x_5"] and x["x_8"] ) or (
                x["x_3"] and x["x_6"] and x["x_9"] ) or (
                x["x_1"] and x["x_5"] and x["x_9"] ) or (
                x["x_3"] and x["x_5"] and x["x_7"] ) or (
                o["o_1"] and o["o_2"] and o["o_3"] ) or (
                o["o_4"] and o["o_5"] and o["o_6"] ) or (
                o["o_7"] and o["o_8"] and o["o_9"] ) or (
                o["o_1"] and o["o_4"] and o["o_7"] ) or (
                o["o_2"] and o["o_5"] and o["o_8"] ) or (
                o["o_3"] and o["o_6"] and o["o_9"] ) or (
                o["o_1"] and o["o_5"] and o["o_9"] ) or (
                o["o_3"] and o["o_5"] and o["o_7"] )) == False  :

            x_order = 0
            while x_order!=1 and x_order!=2 and x_order!=3 and x_order!=4 and x_order!=5 and x_order!=6 and x_order!=7 and x_order!=8 and x_order!=9 :
                print("X", end="")
                short_puse()
                print("\'", end="")
                short_puse()
                print("s", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print("P", end="")
                short_puse()
                print("l", end="")
                short_puse()
                print("a", end="")
                short_puse()
                print("y", end="")
                short_puse()
                print("e", end="")
                short_puse()
                print("r", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print("t", end="")
                short_puse()
                print("u", end="")
                short_puse()
                print("r", end="")
                short_puse()
                print("n", end="")
                short_puse()
                print(".", end="")
                short_puse()
                print(".", end="")
                short_puse()
                print(".", end="")
                x_order = int(input(" "))
                if x_order!=1 and x_order!=2 and x_order!=3 and x_order!=4 and x_order!=5 and x_order!=6 and x_order!=7 and x_order!=8 and x_order!=9 :
                    short_puse()
                    print("",end="I")
                    short_puse()
                    print("",end="n")
                    short_puse()
                    print("",end="v")
                    short_puse()
                    print("",end="a")
                    short_puse()
                    print("",end="l")
                    short_puse()
                    print("",end="i")
                    short_puse()
                    print("",end="d")
                    short_puse()
                    print("",end=" ")
                    short_puse()
                    print("",end="i")
                    short_puse()
                    print("",end="n")
                    short_puse()
                    print("",end="p")
                    short_puse()
                    print("",end="u")
                    short_puse()
                    print("",end="t")
                    short_puse()
                    print("",end=" ")
                    short_puse()
                    print("⚠️")
                    short_puse()
                if x_order==1 :
                    if d["d_1"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i1":"\U0001F7E5"})
                    draw()
                    x.update({"x_1":True})
                    d.update({"d_1":True})
                elif x_order==2 :
                    if d["d_2"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i2":"\U0001F7E5"})
                    draw()
                    x.update({"x_2":True})
                    d.update({"d_2":True})
                elif x_order==3 :
                    if d["d_3"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i3":"\U0001F7E5"})
                    draw()
                    x.update({"x_3":True})
                    d.update({"d_3":True})
                elif x_order==4 :
                    if d["d_4"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i4":"\U0001F7E5"})
                    draw()
                    x.update({"x_4":True})
                    d.update({"d_4":True})
                elif x_order==5 :
                    if d["d_5"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i5":"\U0001F7E5"})
                    draw()
                    x.update({"x_5":True})
                    d.update({"d_5":True})
                elif x_order==6 :
                    if d["d_6"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i6":"\U0001F7E5"})
                    draw()
                    x.update({"x_6":True})
                    d.update({"d_6":True})
                elif x_order==7 :
                    if d["d_7"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i7":"\U0001F7E5"})
                    draw()
                    x.update({"x_7":True})
                    d.update({"d_7":True})
                elif x_order==8 :
                    if d["d_8"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i8":"\U0001F7E5"})
                    draw()
                    x.update({"x_8":True})
                    d.update({"d_8":True})
                elif x_order==9 :
                    if d["d_9"] == True :
                        already()
                        x_order = 0
                        continue
                    print_list.update({"i9":"\U0001F7E5"})
                    draw()
                    x.update({"x_9":True})
                    d.update({"d_9":True})

            if(( x["x_1"] and x["x_2"] and x["x_3"] ) or (
                x["x_4"] and x["x_5"] and x["x_6"] ) or (
                x["x_7"] and x["x_8"] and x["x_9"] ) or (
                x["x_1"] and x["x_4"] and x["x_7"] ) or (
                x["x_2"] and x["x_5"] and x["x_8"] ) or (
                x["x_3"] and x["x_6"] and x["x_9"] ) or (
                x["x_1"] and x["x_5"] and x["x_9"] ) or (
                x["x_3"] and x["x_5"] and x["x_7"] ))==True :
                print()
                short_puse()
                print("+", end="")
                fortyfive = 0
                while fortyfive < 43:
                    print("-", end="")
                    short_puse()
                    fortyfive += 1
                print("+")
                short_puse()
                print("|           ", end="")
                puse()
                print("\U0001F389", end="")
                puse()
                print(" ", end="")
                puse()
                print("P", end="")
                puse()
                print("l", end="")
                puse()
                print("a", end="")
                puse()
                print("y", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("\'", end="")
                puse()
                print("X", end="")
                puse()
                print("\'", end="")
                puse()
                print(" ", end="")
                puse()
                print("W", end="")
                puse()
                print("O", end="")
                puse()
                print("N", end="")
                puse()
                print(" ", end="")
                puse()
                print("!", end="")
                puse()
                print(" ", end="")
                puse()
                print("\U0001F389", end="")
                puse()
                print("           |")
                short_puse()
                print("+", end="")
                fortyfive = 0
                while fortyfive < 43:
                    print("-", end="")
                    short_puse()
                    fortyfive += 1
                print("+")
                short_puse()
                print()
                x_point += 1
                break


            if  ( d["d_1"] and d["d_2"] and d["d_3"] and d["d_4"] and d["d_5"] and d["d_6"] and d["d_7"] and d["d_8"] and d["d_9"] ) :
                print()
                short_puse()
                print("+", end="")
                fortyfive = 0
                while fortyfive < 43:
                    print("-", end="")
                    short_puse()
                    fortyfive += 1
                print("+")
                short_puse()
                print("|                   ",end="")
                puse()
                print("D",end="")
                puse()
                print("R",end="")
                puse()
                print("A",end="")
                puse()
                print("W",end="")
                puse()
                print("!",end="")
                puse()
                print("                   |")
                short_puse()
                print("+", end="")
                fortyfive = 0
                while fortyfive < 43:
                    print("-", end="")
                    short_puse()
                    fortyfive += 1
                print("+")
                short_puse()
                print()
                break

            o_order = 0
            while o_order != 1 and o_order != 2 and o_order != 3 and o_order != 4 and o_order != 5 and o_order != 6 and o_order != 7 and o_order != 8 and o_order != 9:
                print("O", end="")
                short_puse()
                print("\'", end="")
                short_puse()
                print("s", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print("P", end="")
                short_puse()
                print("l", end="")
                short_puse()
                print("a", end="")
                short_puse()
                print("y", end="")
                short_puse()
                print("e", end="")
                short_puse()
                print("r", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print("t", end="")
                short_puse()
                print("u", end="")
                short_puse()
                print("r", end="")
                short_puse()
                print("n", end="")
                short_puse()
                print(".", end="")
                short_puse()
                print(".", end="")
                short_puse()
                print(".", end="")
                o_order = int(input(" "))
                if o_order != 1 and o_order != 2 and o_order != 3 and o_order != 4 and o_order != 5 and o_order != 6 and o_order != 7 and o_order != 8 and o_order != 9 :
                    short_puse()
                    print("",end="I")
                    short_puse()
                    print("",end="n")
                    short_puse()
                    print("",end="v")
                    short_puse()
                    print("",end="a")
                    short_puse()
                    print("",end="l")
                    short_puse()
                    print("",end="i")
                    short_puse()
                    print("",end="d")
                    short_puse()
                    print("",end=" ")
                    short_puse()
                    print("",end="i")
                    short_puse()
                    print("",end="n")
                    short_puse()
                    print("",end="p")
                    short_puse()
                    print("",end="u")
                    short_puse()
                    print("",end="t")
                    short_puse()
                    print("",end=" ")
                    short_puse()
                    print("⚠️")
                    short_puse()
                if o_order == 1:
                    if d["d_1"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i1": "\U0001F7E8"})
                    draw()
                    o.update({"o_1": True})
                    d.update({"d_1": True})
                elif o_order == 2:
                    if d["d_2"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i2": "\U0001F7E8"})
                    draw()
                    o.update({"o_2": True})
                    d.update({"d_2": True})
                elif o_order == 3:
                    if d["d_3"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i3": "\U0001F7E8"})
                    draw()
                    o.update({"o_3": True})
                    d.update({"d_3": True})
                elif o_order == 4:
                    if d["d_4"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i4": "\U0001F7E8"})
                    draw()
                    o.update({"o_4": True})
                    d.update({"d_4": True})
                elif o_order == 5:
                    if d["d_5"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i5": "\U0001F7E8"})
                    draw()
                    o.update({"o_5": True})
                    d.update({"d_5": True})
                elif o_order == 6:
                    if d["d_6"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i6": "\U0001F7E8"})
                    draw()
                    o.update({"o_6": True})
                    d.update({"d_6": True})
                elif o_order == 7:
                    if d["d_7"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i7": "\U0001F7E8"})
                    draw()
                    o.update({"o_7": True})
                    d.update({"d_7": True})
                elif o_order == 8:
                    if d["d_8"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i8": "\U0001F7E8"})
                    draw()
                    o.update({"o_8": True})
                    d.update({"d_8": True})
                elif o_order == 9:
                    if d["d_9"] == True:
                        already()
                        o_order = 0
                        continue
                    print_list.update({"i9": "\U0001F7E8"})
                    draw()
                    o.update({"o_9": True})
                    d.update({"d_9": True})


            if (( o["o_1"] and o["o_2"] and o["o_3"] ) or (
                o["o_4"] and o["o_5"] and o["o_6"] ) or (
                o["o_7"] and o["o_8"] and o["o_9"] ) or (
                o["o_1"] and o["o_4"] and o["o_7"] ) or (
                o["o_2"] and o["o_5"] and o["o_8"] ) or (
                o["o_3"] and o["o_6"] and o["o_9"] ) or (
                o["o_1"] and o["o_5"] and o["o_9"] ) or (
                o["o_3"] and o["o_5"] and o["o_7"] )) == True :
                print()
                short_puse()
                print("+", end="")
                fortyfive = 0
                while fortyfive < 43:
                    print("-", end="")
                    short_puse()
                    fortyfive += 1
                print("+")
                short_puse()
                print("|           ", end="")
                puse()
                print("\U0001F389", end="")
                puse()
                print(" ", end="")
                puse()
                print("P", end="")
                puse()
                print("l", end="")
                puse()
                print("a", end="")
                puse()
                print("y", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("\'", end="")
                puse()
                print("O", end="")
                puse()
                print("\'", end="")
                puse()
                print(" ", end="")
                puse()
                print("W", end="")
                puse()
                print("O", end="")
                puse()
                print("N", end="")
                puse()
                print(" ", end="")
                puse()
                print("!", end="")
                puse()
                print(" ", end="")
                puse()
                print("\U0001F389", end="")
                puse()
                print("           |")
                short_puse()
                print("+", end="")
                fortyfive = 0
                while fortyfive < 43:
                    print("-", end="")
                    short_puse()
                    fortyfive += 1
                print("+")
                short_puse()
                print()
                o_point += 1
                break


        puse()
        print("D", end="")
        puse()
        print("o", end="")
        puse()
        print(" ", end="")
        puse()
        print("y", end="")
        puse()
        print("o", end="")
        puse()
        print("u", end="")
        puse()
        print(" ", end="")
        puse()
        print("w", end="")
        puse()
        print("a", end="")
        puse()
        print("n", end="")
        puse()
        print("t", end="")
        puse()
        print(" ", end="")
        puse()
        print("t", end="")
        puse()
        print("o", end="")
        puse()
        print(" ", end="")
        puse()
        print("p", end="")
        puse()
        print("l", end="")
        puse()
        print("a", end="")
        puse()
        print("y", end="")
        puse()
        print(" ", end="")
        puse()
        print("a", end="")
        puse()
        print("g", end="")
        puse()
        print("a", end="")
        puse()
        print("i", end="")
        puse()
        print("n", end="")
        puse()
        print(" ", end="")
        puse()
        # print("‹", end="")
        # puse()
        # print(" ", end="")
        # puse()
        # print("\U0001F1F5", end="")
        # puse()
        # print("\U0001F1F7", end="")
        # puse()
        # print("\U0001F1EE", end="")
        # puse()
        # print("\U0001F1F3", end="")
        # puse()
        # print("\U0001F1F9", end="")
        # puse()
        # print(" ", end="")
        # puse()
        # print("\U0001F1FE", end="")
        # puse()
        # print("\U0001F1EA", end="")
        # puse()
        # print("\U0001F1F8", end="")
        # puse()
        # print(" ", end="")
        # puse()
        # print("\U0001F1F4", end="")
        # puse()
        # print("\U0001F1F7", end="")
        # puse()
        # print(" ", end="")
        # puse()
        # print("\U0001F1F3", end="")
        # puse()
        # print("\U0001F1F4", end="")
        # puse()
        # print(" ", end="")
        # puse()
        # print("›", end="")
        # puse()
        print(" ", end="")
        puse()
        print("?", end="")
        puse()
        print(" ", end="")
        r_e_p_e_a_t = input("")
        r_e_p_e_a_t = r_e_p_e_a_t.lower()
        r_e_p_e_a_t__cheacker = 0

        while r_e_p_e_a_t != 'yes' and r_e_p_e_a_t != 'no':
            if r_e_p_e_a_t__cheacker == 0:
                puse()
                print("P", end="")
                puse()
                print("l", end="")
                puse()
                print("e", end="")
                puse()
                print("a", end="")
                puse()
                print("s", end="")
                puse()
                print("e", end="")
                puse()
                print(" ", end="")
                puse()
                print("e", end="")
                puse()
                print("n", end="")
                puse()
                print("t", end="")
                puse()
                print("e", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("\'", end="")
                puse()
                print("Y", end="")
                puse()
                print("e", end="")
                puse()
                print("s", end="")
                puse()
                print("\'", end="")
                puse()
                print(" ", end="")
                puse()
                print("o", end="")
                puse()
                print("r", end="")
                puse()
                print(" ", end="")
                puse()
                print("\'", end="")
                puse()
                print("N", end="")
                puse()
                print("o", end="")
                puse()
                print("\'", end="")
                puse()
                print(" ", end="")
                puse()
                print(":", end="")
                puse()
                print(" ", end="")
            else:
                puse()
                print("P", end="")
                short_puse()
                print("l", end="")
                short_puse()
                print("e", end="")
                short_puse()
                print("a", end="")
                short_puse()
                print("s", end="")
                short_puse()
                print("e", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print("e", end="")
                short_puse()
                print("n", end="")
                short_puse()
                print("t", end="")
                short_puse()
                print("e", end="")
                short_puse()
                print("r", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print("\'", end="")
                short_puse()
                print("Y", end="")
                short_puse()
                print("e", end="")
                short_puse()
                print("s", end="")
                short_puse()
                print("\'", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print("o", end="")
                short_puse()
                print("r", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print("\'", end="")
                short_puse()
                print("N", end="")
                short_puse()
                print("o", end="")
                short_puse()
                print("\'", end="")
                short_puse()
                print(" ", end="")
                short_puse()
                print(":", end="")
                short_puse()
                print(" ", end="")
            r_e_p_e_a_t = input("")
            r_e_p_e_a_t = r_e_p_e_a_t.lower()
            r_e_p_e_a_t__cheacker = 1


        if r_e_p_e_a_t == 'yes' :
            repeat = 'YES'
        elif r_e_p_e_a_t == 'no' :
            print()
            short_puse()
            print("+", end="")
            fortyfive = 0
            while fortyfive < 43:
                print("-", end="")
                short_puse()
                fortyfive += 1
            print("+")
            print("|           ", end="")
            puse()
            print("T", end="")
            puse()
            print("h", end="")
            puse()
            print("a", end="")
            puse()
            print("n", end="")
            puse()
            print("k", end="")
            puse()
            print(" ", end="")
            puse()
            print("y", end="")
            puse()
            print("o", end="")
            puse()
            print("u", end="")
            puse()
            print(" ", end="")
            puse()
            print("f", end="")
            puse()
            print("o", end="")
            puse()
            print("r", end="")
            puse()
            print(" ", end="")
            puse()
            print("p", end="")
            puse()
            print("l", end="")
            puse()
            print("a", end="")
            puse()
            print("y", end="")
            puse()
            print("i", end="")
            puse()
            print("n", end="")
            puse()
            print("g", end="")
            puse()
            print("           |")
            short_puse()
            print("+", end="")
            fortyfive = 0
            while fortyfive < 43:
                print("-", end="")
                short_puse()
                fortyfive += 1
            print("+")
            short_puse()
            print()
            repeat = 'NO'
except:
    print("\n﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏")
    print("‹‹‹  \U0001F1F8\U0001F1F4\U0001F1F2\U0001F1EA\U0001F1F9\U0001F1ED\U0001F1EE\U0001F1F3\U0001F1EC \U0001F1FC\U0001F1EA\U0001F1F3\U0001F1F9 \U0001F1FC\U0001F1F7\U0001F1F4\U0001F1F3\U0001F1EC. \U0001F1F5\U0001F1F1\U0001F1EA\U0001F1E6\U0001F1F8\U0001F1EA \U0001F1F7\U0001F1EA\U0001F1F7\U0001F1FA\U0001F1F3 \U0001F1F5\U0001F1F7\U0001F1F4\U0001F1EC\U0001F1F7\U0001F1E6\U0001F1F2  ›››")
    print("﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏﹏\n")